site_name: CompTIA Linux+ (XK0-005)
site_description: CompTIA Linux+ (XK0-005)
site_author: Georgette Webb

theme:
  name: material
  #favicon: images/favicon.png
  include_sidebar: true
  # extra_css:
  #   - css/responsive.css

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.instant
    - navigation.top
    - toc.integrate
    - announce.dismiss    
    - search.suggest
    - search.share
    - search.highlight
    - content.tabs.link
    - content.tooltips
    - content.code.select
    - content.code.annotation
    - content.code.copy
  language: en
  icon:
    logo: simple/awslambda
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: blue
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: blue
      accent: lime

# pages:
#   - 404: '404.md'

nav:
  - home: index.md
  - Introduction to Linux+: '00-introduction-to-linux-plus/index.md'
  - Understand Linux Fundamentals: '01-understand-linux-fundamentals/index.md'
  - Understand the Linux Boot Process and Hardware: '02-understand-linux-boot-process-and-hardware/index.md'
  - Understand Package Compilation and Storage Concepts: '03-understand-package-compilation-and-storage-concepts/index.md'
  - Edit Files on Linux Systems: '04-edit-files-on-linux-systems/index.md'
  - Compress, Backup and Archive Files: '05-compress-backup-and-archive-files/index.md'
  - Understand File and Directory Operations: '06-understand-file-and-directory-operations/index.md'
  - Manage and Transfer Files: '07-manage-and-transfer-files/index.md'
  - Understand Partitions and Monitor Storage: '08-understand-partitions-and-monitor-storage/index.md'
  - Create and Mount Filesystems: '09-create-and-mount-filesystems/index.md'
  - Understand Logical Volume Management & LUKS: '10-understand-logical-volume-management-and-luks/index.md'
  - Understanding Network Storage and Shares: '11-understanding-network-storage-and-shares/index.md'
  - Manage and Schedule Services: '12-manage-and-schedule-services/index.md'
  - Manage Linux Processes: '13-manage-linux-processes/index.md'
  - Manage Network Interfaces: '14-manage-network-interfaces/index.md'
  - Understand Name Resolution: '15-understand-name-resolution/index.md'
  - Monitor Networks: '16-monitor-networks/index.md'
  - Understand Package Management: '17-understand-package-management/index.md'
  - Packages, System Configurations & Localization: '18-packages-system-configurations-and-localization/index.md'
  - Configure Kernel Options and System Services: '19-configure-kernel-options-and-system-services/index.md'
  - Understand Cryptography and Certificates: '20-understand-cryptography-and-certificates/index.md'
  - Understand Authentication: '21-understand-authentication/index.md'
  - Harden Linux Systems: '22-harden-linux-systems/index.md'
  - Implement Identity Management: '23-implement-identity-management/index.md'
  - Configure Firewalls: '24-configure-firewalls/index.md'
  - Configure and Execute Remote Connectivity: '25-configure-and-execute-remote-connectivity/index.md'
  - Understand Security-Enhanced Linux & Access Control: '26-understand-security-enhanced-linux-and-access-control/index.md'
  - Understand Permissions: '27-understand-permissions/index.md'
  - Automate Tasks with Shell Scripts: '28-automate-tasks-with-shell-scripts/index.md'
  - Perform Basic Version Control: '29-perform-basic-version-control/index.md'
  - Understand Container, Cloud and Orchestration Concepts: '30-understand-container-cloud-and-orchestration-concepts/index.md'
  - Understand Infrastructure As Code Technologies: '31-understand-infrastructure-as-code-technologies/index.md'
  - Troubleshoot Network Resource Issues: '32-troubleshoot-network-resource-issues/index.md'
  - Troubleshoot Storage and CPU Issues: '33-troubleshoot-storage-and-cpu-issues/index.md'
  - Use Systemd to Resolve Common Problems: '34-use-systemd-to-resolve-common-problems/index.md'
  - Troubleshoot Device and User Issues: '35-troubleshoot-device-and-user-issues/index.md'



# plugins:
#   - typeset:
#       enabled: true
#   - privacy

markdown_extensions:
  - admonition
  - tables
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  # - toc:
  #     permalink: true

copyright: |
  Copyright &copy; 2023 Georgette Webb

extra:
  generator: false